#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $AIRFLOW_USER WITH PASSWORD '$AIRFLOW_PASSWORD';
    CREATE DATABASE $AIRFLOW_DB OWNER $AIRFLOW_USER;
    GRANT ALL PRIVILEGES ON DATABASE $AIRFLOW_DB TO $AIRFLOW_USER;

    CREATE USER $DWH_USER WITH PASSWORD '$DWH_PASSWORD';
    CREATE DATABASE $DWH_DB OWNER $DWH_USER;
    GRANT ALL PRIVILEGES ON DATABASE $DWH_DB TO $DWH_USER;
	\c dwh
	CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION $DWH_USER;
EOSQL